stages:
  - deploy

# Select image from https://hub.docker.com/_/php/
image: php:7.3-cli

# Select what we should cache
cache:
  paths:
    - vendor/
    - node_modules/

variables:
  RELEASES: "$REMOTE_BASE/releases"
  SHARED: "$REMOTE_BASE/shared"

before_script:
  # setup SSH & private key
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -yqq )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh; chmod 700 ~/.ssh
  - ssh-keyscan -p $REMOTE_PORT $REMOTE_SERVER >> ~/.ssh/known_hosts
  # the following line is optional (likely remove previous line)
  #- echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  # Install packages
  - apt-get install gnupg2 build-essential libssl-dev -yqq
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  # Install git, the php image doesn't have installed
  - apt-get install git zip unzip gcc g++ make nodejs -yqq
  - alias nodejs=node
  # add package key for yarn
  - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt-get update -yqq && apt-get install yarn -yqq
  - curl -sS https://getcomposer.org/installer | php

deploy:
  stage: deploy
  when: manual
  allow_failure: false
  script:
    - export APP_ENV=prod
    - php -v
    - php composer.phar --version
    - node --version
    - yarn --version
    # setup vars for paths
    - TIMESTAMP=$(date +%s); RELEASE="$RELEASES/$TIMESTAMP"
    - echo "Paths:"; echo $REMOTE_BASE; echo $RELEASE; echo $SHARED
    - echo "Remote:"; echo $REMOTE_USER@$REMOTE_SERVER:$REMOTE_PORT
    # install php dependencies
    - php composer.phar install --no-dev --classmap-authoritative --no-interaction --no-progress --no-scripts --no-plugins
    # Install node/JS dependencies
    - yarn install --non-interactive --frozen-lockfile
    - yarn build
    # add .revision file
    - git rev-parse --verify --short HEAD > .revision
    # ensure based paths exist
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "mkdir -p $RELEASES $SHARED $SHARED/var $SHARED/public/uploads $SHARED/public/media/cache"
    # sync files to release directory
    - rsync --archive --stats --human-readable --no-perms --exclude ".git/" --exclude ".idea/" --exclude "node_modules/" -e "ssh -p $REMOTE_PORT" . $REMOTE_USER@$REMOTE_SERVER:$RELEASE
    # copy env file into place
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cp -a $SHARED/.env $RELEASE/.env"
    # link shared folders
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "rm -rf $RELEASE/var; ln -s $SHARED/var $RELEASE/var; rm -rf $RELEASE/public/uploads; ln -s $SHARED/public/uploads $RELEASE/public/uploads; rm -rf $RELEASE/public/media/cache; ln -s $SHARED/public/media/cache $RELEASE/public/media/cache"
    # switch to new version; run composer on server; db migrations
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "rm -f $REMOTE_BASE/current; ln -s $RELEASE $REMOTE_BASE/current; cd $REMOTE_BASE/current; export APP_ENV=prod; php composer.phar run-script post-update-cmd"
    # clear opcache
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "cd $RELEASE; echo '<?php opcache_reset();' > html/opcache_reset.php; curl $HTTP_ROOT/opcache_reset.php; rm html/opcache_reset.php" || echo -e "\033[0;31mFAILURE unable to reset OPcache"
    # supervisord: write config & restart all
    - php bin/console app:supervisor:write-config; php bin/console app:supervisor:restart --all
    # cloudflare: purge cache
    #- php bin/console app:cloudflare:purge-cache
    # remove >3 releases
    - ssh -p $REMOTE_PORT $REMOTE_USER@$REMOTE_SERVER "ls -1d $RELEASES/* | sort -rg | tail -n +4 | xargs /bin/rm -rf"
